[1347] feat: reschedule buttons, tables fixing, meta tags editing panel, flo…
QualityUnit/wp-urlslab pull request #1019
Opened 2023-08-02 13:15 UTC by jremen

reschedule buttons, tables fixing, meta tags editing panel, floating row actions buttons

Close QualityUnit/web-issues#1347

2023-08-02 15:52 UTC, ihdk requested changes
I just noticed some css issues with table "infinite" horizontal scroll, video descrobe the best: https://app.screencast.com/5FZ8edpl0DT2B

otherwise I have no comments to code itself....

2023-08-03 09:23 UTC, ihdk requested changes
it's still the same with table on my side: https://app.screencast.com/bzVmvt18lSe1S
have checked and using most recent not cached css

Also warnings during build, double default export of the same module:
```
Export "default" of module "src/elements/RowActionButtons.jsx" was reexported through module "src/lib/tableImports.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is 
not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "src/modules/static/TagsLabels.jsx" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.

```

2023-08-03 12:44 UTC, jremen commented
@ihdk 
Hopefully fixed for now

2023-08-03 12:54 UTC, ihdk submitted a review, later dismissed

2023-08-03 13:16 UTC, mvstepanek approved these changes

2023-08-03 13:16 UTC, merged