[2483] feat: faq shortcode for gutenberg and elementor
QualityUnit/wp-urlslab pull request #1665
Opened 2024-02-01 09:46 UTC by jremen

**Changes proposed in this Pull Request**
faq shortcode for gutenberg and elementor

Close QualityUnit/web-issues#2483

2024-02-01 14:55 UTC, ihdk requested changes
when url is not filled, should be used current page url: https://github.com/QualityUnit/web-issues/issues/2483#issuecomment-1920813330

Now, without url defined, shortcode using empty url parameter `url=""`

Also, we could use number inputs for parameters that expect number, currently any string can be passed to shortcode as "Number of FAQs".

2024-02-02 05:30 UTC, vzeman requested changes

2024-02-02 05:30 UTC, vzeman commented on blocks/includes/blocks/class-urlslab-faqs.php
> +class Urlslab_FAQs extends Urlslab_Gutenberg_Block {
fix all names of classes 
Correct classname should be e.g.  Urlslab_Blocks_Faqs

2024-02-02 05:58 UTC, ihdk commented
> @ihdk if url is empty, it will be filled in automatically by plugin!

ok then, I thought it has to be filled before `do_shortcode` in that case...

2024-02-06 08:59 UTC, ihdk approved these changes

2024-02-06 09:38 UTC, ihdk approved these changes

2024-02-06 09:55 UTC, merged