[1477] url changes panel
QualityUnit/wp-urlslab pull request #883
Opened 2023-06-28 10:21 UTC by jremen

**Changes proposed in this Pull Request**
URL changes panel comparator

Close QualityUnit/web-issues#1477

2023-06-29 06:37 UTC, ihdk commented
@jremen 
Not sure if it's something that should be or will be resolved, so just ask:

[#1477](https://github.com/QualityUnit/web-issues/issues/1477) - shouldn't be edited generator result immediately reflected on edited row in table after save in popup? now, manual table refresh is necessary to see the change.

[#1645](https://github.com/QualityUnit/web-issues/issues/1645) - this works with invalidated modules query, maybe we can later remove unnecessray rerender and flashing of modules and header bottom after activation/deactivation...
I have it done locally with few simple changes using memoization and `fetchedModules` saved into store. Data are not passed deeply into `<MainMenu>` and `<DynamicModule>` unnecessary via props. 
Query invalidation cause rerender of whole `<DynamicModule>` thus flashing of modules and header bottom with fade in animation...

Except these things it can be approved, I do not have any comments...

2023-07-01 16:13 UTC, vzeman requested changes

2023-07-01 16:13 UTC, vzeman commented on admin/src/api/importCsv.js
> +	result( 1 );
@jremen naco je tento return? debugovaci? alebo ma zmysel?

2023-07-01 16:35 UTC, jremen commented on admin/src/api/importCsv.js
> +	result( 1 );
@vzeman
Aby po zaciatku importu necakalo na prvy response z Fetch ale hned zobrazilo na 1% progress bar

2023-07-01 17:05 UTC, vzeman approved these changes

2023-07-01 20:18 UTC, ihdk commented
@vzeman sorac omylom som na mobile klikol request ked som si to tu prezeral co sa deje...

2023-07-02 19:09 UTC, merged