[1366] settings labels
QualityUnit/wp-urlslab pull request #998
Opened 2023-08-01 14:02 UTC by jremen

**Changes proposed in this Pull Request**
settings labels

Close QualityUnit/web-issues#1366

2023-08-01 16:23 UTC, ihdk submitted a review, later dismissed

2023-08-02 05:13 UTC, vzeman requested changes
I have checked design of labels and on multiple places it doesn't look good.
I suggest to make smaller height of labels next to each setting and also smaller font
also spacing between next elements should be set correctly

also it looks to me, that text in label is not centered

![Screenshot from 2023-08-02 07-12-48](https://github.com/QualityUnit/wp-urlslab/assets/6470030/e646c2ac-f8e1-4325-9d24-dc541eafde0b)

2023-08-02 06:27 UTC, jremen commented
@vzeman 
Labels next to settings options (inputs, menus, switches) are now smaller. Same size 12px for labels under main settings section description (on the left)

2023-08-02 07:24 UTC, mvstepanek approved these changes

2023-08-02 07:25 UTC, merged